--  admin
CREATE TABLE admin
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE
);

--  users
CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    password VARCHAR(255),
    phone_number VARCHAR(255),
    username VARCHAR(255),
    is_verified BOOLEAN
);

--  verification_tokens
CREATE TABLE verification_tokens
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMP(6) NOT NULL,
    token VARCHAR(255) NOT NULL,
    user_id BIGINT UNIQUE REFERENCES users(id)
);
